version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: medisuiv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questionnairesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mongo:
    image: mongo:7
    container_name: medisuiv-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: medisuiv-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: medisuiv-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8087:8080"
    volumes:
      - ./infra/keycloak/realm:/opt/keycloak/data/import:ro
      - ./infra/keycloak/themes:/opt/keycloak/themes:ro

  eureka-server:
    build:
      context: ./eureka-server
    container_name: medisuiv-eureka
    ports:
      - "8761:8761"

  config-server:
    build:
      context: ./config-server
    container_name: medisuiv-config
    depends_on:
      - eureka-server
    ports:
      - "8888:8888"

  questionnaires-service:
    build:
      context: ./questionnaires-service
    container_name: medisuiv-questionnaires
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
      - config-server
      - keycloak
    ports:
      - "8085:8085"

  dashboards-service:
    build:
      context: ./dashboards-service
    container_name: medisuiv-dashboards
    depends_on:
      - mongo
      - rabbitmq
      - eureka-server
      - config-server
      - keycloak
    ports:
      - "8086:8086"

  notifications-service:
    build:
      context: ./notifications-service
    container_name: medisuiv-notifications
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
      - config-server
      - keycloak
    ports:
      - "8088:8088"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: medisuiv-gateway
    depends_on:
      - questionnaires-service
      - dashboards-service
      - notifications-service
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: medisuiv-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.2.0
    container_name: medisuiv-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  postgres_data:
  mongo_data:
