server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notificationsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/medisuiv-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
